### ISSUE TITLE
Error in macstrap config/settings.json file for VS Code 

### ISSUE THREAD

**Issue by MatthewNielsen27** [azohra/macstrap#2]
There is a comma missing at the end of line 73 that makes users lose functionality in VS Code

`73: terminal.integrated.fontFamily": "Knack Nerd Font, Menlo,DejaVu Sans Mono, Consolas,Lucida Console, monospace`

**Comment by tk8817** [comment]
@MatthewNielsen27 - would you be able to open a PR to address this issue?
